/*
 * NetBox API
 *
 * API to access NetBox
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */
use serde_json::Value;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceNapalm {
    #[serde(rename = "method")]
    pub method: ::std::collections::HashMap<String, Value>,
}

impl DeviceNapalm {
    pub fn new(method: ::std::collections::HashMap<String, Value>) -> DeviceNapalm {
        DeviceNapalm { method }
    }
}
