/*
 * NetBox API
 *
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.7
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceRole {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "color")]
    pub color: String,
    /// Virtual machines may be assigned to this role
    #[serde(rename = "vm_role", skip_serializing_if = "Option::is_none")]
    pub vm_role: Option<bool>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "device_count", skip_serializing_if = "Option::is_none")]
    pub device_count: Option<i32>,
    #[serde(rename = "virtualmachine_count", skip_serializing_if = "Option::is_none")]
    pub virtualmachine_count: Option<i32>,
}

impl DeviceRole {
    pub fn new(name: String, slug: String, color: String) -> DeviceRole {
        DeviceRole {
            id: None,
            name,
            slug,
            color,
            vm_role: None,
            description: None,
            device_count: None,
            virtualmachine_count: None,
        }
    }
}


