/*
 * NetBox API
 *
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.7
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IpAddressInterface {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "device", skip_serializing_if = "Option::is_none")]
    pub device: Option<Box<crate::models::NestedDevice>>,
    #[serde(rename = "virtual_machine", skip_serializing_if = "Option::is_none")]
    pub virtual_machine: Option<Box<crate::models::NestedVirtualMachine>>,
    #[serde(rename = "name")]
    pub name: String,
}

impl IpAddressInterface {
    pub fn new(name: String) -> IpAddressInterface {
        IpAddressInterface {
            id: None,
            url: None,
            device: None,
            virtual_machine: None,
            name,
        }
    }
}
