/*
 * NetBox API
 *
 * API to access NetBox
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelType {
    #[serde(rename = "label")]
    pub label: Label,
    #[serde(rename = "value")]
    pub value: Value,
}

impl ModelType {
    pub fn new(label: Label, value: Value) -> ModelType {
        ModelType { label, value }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Label {
    #[serde(rename = "DE-9")]
    DE9,
    #[serde(rename = "DB-25")]
    DB25,
    #[serde(rename = "RJ-11")]
    RJ11,
    #[serde(rename = "RJ-12")]
    RJ12,
    #[serde(rename = "RJ-45")]
    RJ45,
    #[serde(rename = "Mini-DIN 8")]
    MiniDIN8,
    #[serde(rename = "USB Type A")]
    USBTypeA,
    #[serde(rename = "USB Type B")]
    USBTypeB,
    #[serde(rename = "USB Type C")]
    USBTypeC,
    #[serde(rename = "USB Mini A")]
    USBMiniA,
    #[serde(rename = "USB Mini B")]
    USBMiniB,
    #[serde(rename = "USB Micro A")]
    USBMicroA,
    #[serde(rename = "USB Micro B")]
    USBMicroB,
    #[serde(rename = "USB Micro AB")]
    USBMicroAB,
    #[serde(rename = "Other")]
    Other,
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Value {
    #[serde(rename = "de-9")]
    De9,
    #[serde(rename = "db-25")]
    Db25,
    #[serde(rename = "rj-11")]
    Rj11,
    #[serde(rename = "rj-12")]
    Rj12,
    #[serde(rename = "rj-45")]
    Rj45,
    #[serde(rename = "mini-din-8")]
    MiniDin8,
    #[serde(rename = "usb-a")]
    UsbA,
    #[serde(rename = "usb-b")]
    UsbB,
    #[serde(rename = "usb-c")]
    UsbC,
    #[serde(rename = "usb-mini-a")]
    UsbMiniA,
    #[serde(rename = "usb-mini-b")]
    UsbMiniB,
    #[serde(rename = "usb-micro-a")]
    UsbMicroA,
    #[serde(rename = "usb-micro-b")]
    UsbMicroB,
    #[serde(rename = "usb-micro-ab")]
    UsbMicroAb,
    #[serde(rename = "other")]
    Other,
}
