/*
 * NetBox API
 *
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.7
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RackReservation {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "rack")]
    pub rack: Box<crate::models::NestedRack>,
    #[serde(rename = "units")]
    pub units: Vec<i32>,
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    #[serde(rename = "user")]
    pub user: Box<crate::models::NestedUser>,
    #[serde(rename = "tenant", skip_serializing_if = "Option::is_none")]
    pub tenant: Option<Box<crate::models::NestedTenant>>,
    #[serde(rename = "description")]
    pub description: String,
}

impl RackReservation {
    pub fn new(
        rack: crate::models::NestedRack,
        units: Vec<i32>,
        user: crate::models::NestedUser,
        description: String,
    ) -> RackReservation {
        RackReservation {
            id: None,
            rack: Box::new(rack),
            units,
            created: None,
            user: Box::new(user),
            tenant: None,
            description,
        }
    }
}
