/*
 * NetBox API
 *
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.7
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretRole {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "secret_count", skip_serializing_if = "Option::is_none")]
    pub secret_count: Option<i32>,
}

impl SecretRole {
    pub fn new(name: String, slug: String) -> SecretRole {
        SecretRole {
            id: None,
            name,
            slug,
            description: None,
            secret_count: None,
        }
    }
}
