/*
 * NetBox API
 *
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.7
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Width {
    #[serde(rename = "label")]
    pub label: Label,
    #[serde(rename = "value")]
    pub value: i32,
}

impl Width {
    pub fn new(label: Label, value: i32) -> Width {
        Width { label, value }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Label {
    #[serde(rename = "10 inches")]
    _10Inches,
    #[serde(rename = "19 inches")]
    _19Inches,
    #[serde(rename = "23 inches")]
    _23Inches,
}
