/*
 * NetBox API
 *
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.7
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WritableRegion {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
    pub parent: Option<i32>,
    #[serde(rename = "site_count", skip_serializing_if = "Option::is_none")]
    pub site_count: Option<i32>,
}

impl WritableRegion {
    pub fn new(name: String, slug: String) -> WritableRegion {
        WritableRegion {
            id: None,
            name,
            slug,
            parent: None,
            site_count: None,
        }
    }
}
